version: "3"
services:
  poll:
    build: poll
    image: poll
    depends_on:
      - redis
    ports:
      - "5000:80"
    networks:
      - poll-tier

  redis:
    image: redis
    ports: 
      - "6379"
    networks:
      - poll-tier
      - back-tier

  worker:
    build: worker
    image: worker
    depends_on:
      - redis
      - db
    networks:
      - back-tier

  db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - result-tier
      - back-tier
  
  result:
    build: result
    image: result
    depends_on:
      - db
    ports:
      - "5001:80"
    networks:
      - result-tier

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data:
